/* CREATE DATABASE */
CREATE DATABASE IF NOT EXISTS PERSONALISED_OFFER_DB;

/* USE DATABASE */
USE PERSONALISED_OFFER_DB;
	
/* DROP TABLE IF EXIST ANCILLARY_DETAILS */
DROP TABLE IF EXISTS ANCILLARY_DETAILS;

/* CREATE TABLE ANCILLARY_DETAILS */
CREATE TABLE ANCILLARY_DETAILS(
	ANCILLARY_ID INT(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ANCILLARY_NAME VARCHAR(50) NOT NULL UNIQUE,
	ANCILLARY_DESC VARCHAR(200)
);
	
/* DROP TABLE IF EXIST PREFFERED_ANCILLARY */
DROP TABLE IF EXISTS PREFFERED_ANCILLARY;

/* CREATE TABLE PREFFERED_ANCILLARY_DETAILS */
CREATE TABLE PREFFERED_ANCILLARY(
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	ORIGIN_AIRPORT_CODE VARCHAR(5) NOT NULL,
	DEST_AIRPORT_CODE VARCHAR(5) NOT NULL,
	ANCILLARY_ID INT(3) NOT NULL,
	ANCILLARY_COUNT INT(5) NOT NULL,
    FOREIGN KEY (ANCILLARY_ID) REFERENCES ANCILLARY_DETAILS (ANCILLARY_ID)
		ON UPDATE CASCADE ON DELETE CASCADE
);

/* SHOW ALL TABLES */
SHOW TABLES;

/* INSERT INTO ANCILLARY_DETAILS TABLE */
INSERT INTO ANCILLARY_DETAILS VALUES (101, 'WiFi', 'Wifi available inside');
INSERT INTO ANCILLARY_DETAILS VALUES (102, 'Trip Insurance', 'Trip Insurence');
INSERT INTO ANCILLARY_DETAILS VALUES (103, 'Bags', 'Baggages');
INSERT INTO ANCILLARY_DETAILS VALUES (104, 'Paid seat', 'Paid seat');
INSERT INTO ANCILLARY_DETAILS VALUES (105, 'Skyclub', 'Skyclub one day pass');

/* INSERT INTO PREFFERED_ANCILLARY TABLE */
INSERT INTO PREFFERED_ANCILLARY VALUES ('MSPDTW101', 'MSP', 'DTW', 101, 137);
INSERT INTO PREFFERED_ANCILLARY VALUES ('MSPDTW102', 'MSP', 'DTW', 102, 125);
INSERT INTO PREFFERED_ANCILLARY VALUES ('MSPDTW103', 'MSP', 'DTW', 103, 12);
INSERT INTO PREFFERED_ANCILLARY VALUES ('ATLJFK104', 'ATL', 'JFK', 104, 240);
INSERT INTO PREFFERED_ANCILLARY VALUES ('ATLJFK105', 'ATL', 'JFK', 105, 210);
INSERT INTO PREFFERED_ANCILLARY VALUES ('ATLJFK103', 'ATL', 'JFK', 103, 51);

/* SELECT QUERY FROM ALL TABLE */
SELECT * FROM ANCILLARY_DETAILS;
SELECT * FROM PREFFERED_ANCILLARY;

SELECT D.ORIGIN_AIRPORT_CODE, D.DEST_AIRPORT_CODE, D.ANCILLARY_ID, A.ANCILLARY_NAME, A.ANCILLARY_DESC FROM PREFFERED_ANCILLARY D JOIN ANCILLARY_DETAILS A ON 
D.ANCILLARY_ID = A.ANCILLARY_ID;